#!/usr/bin/env bash

: "${DOCKER_REPO:?}"

if [[ "${SOURCE_BRANCH+x}" == "x" ]]; then
  DOCKER_TAG=$(echo "$SOURCE_BRANCH" | cut -d'/' -f 2)-$(echo "$SOURCE_BRANCH" | cut -d'/' -f 3)
fi;

: "${DOCKER_TAG:?}"

echo "Check images before retagging: "
docker image ls
echo

if [[ "${COPY_TO_REPO+x}" == "x" ]]; then
  docker image tag "$DOCKER_REPO:$DOCKER_TAG" "$COPY_TO_REPO:$DOCKER_TAG"
  
  echo "Check images after retagging: "
  docker image ls
  echo
  # Push to the copy first so it will exist even if the second push fails
  docker image push "$COPY_TO_REPO:$DOCKER_TAG"
  if [ -f "latest" ]; then
    docker push "$COPY_TO_REPO:latest"
  fi
fi

docker push "$DOCKER_REPO:$DOCKER_TAG"
if [ -f "latest" ]; then
  docker push "$DOCKER_REPO:latest"
fi
